version: '3'

services:
  todos-db:
    image: postgres:15.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    volumes:
      - ./postgres:/var/lib/postgresql/data
